### PR TITLE
Replacing `get` for `graph` in ssb-friends usage

### PR DESCRIPTION
**Pull request by nsantini**
## What's the problem you solved?
Issue #718 reported the issue we got after bumping `ssb-friends` to 5.0.0.

## What solution are you recommending?
This solution replaces the use of the legacy `get` for the new version `graph`. It creates a Promise with the resolved graph and filters it by just the current `id`.
It also updates what is considered "following" and "blocking" based on the new version specs

### CODE REVIEW

**Comment by nsantini** [comment]
@christianbundy @cinnamon-bun Are you guys still actively maintaining Oasis?
I'm keen to try to solve more issues when I find time...

**Comment by nickwynja** [comment]
@nsantini I should be able to take a look at this today. There's not a lot of activity here but a few people are able to merge PRs when others contribute.

**Comment by nickwynja** [comment]
@nsantini I'm having trouble tracking it down exactly but it appears to me so far that no data is syncing when I have this PR checked out. I appear to be connected to peers but no new data is streaming in. Can you double check that you're not seeing that same behavior?

**Comment by nsantini** [comment]
One thing I should improve here: add backwards compatibility. If you are running Oasis on top of say Patchwork, we might encounter the opposite bug, not having access to the new API

I have not encountered the issue you mention @nickwynja

**Comment by nickwynja** [comment]
@nsantini What version of node are you on while running this branch?

**Comment by nsantini** [comment]
Currently v14.16.0, but I think I was running v12 when I did that work

**Comment by nickwynja** [comment]
I can't figure this out. My guess is you're following some pub or room that is replicating while I don't think I have any connections like that.

**Comment by nickwynja** [comment]
I discovered #785 in the closed PRs. With the addition of the other bumped versions, things replicate fine. So I've added those changes and will merge.

**Pull request merged**
