### PR TITLE
Use capitalization for Oasis links and buttons

### PR DESCRIPTION
**Pull request by christianbundy**
Problem: Using all-lowercase-everything isn't really a standard around
the web and it might be better to use consistent capitalization. This
was brought up in: https://github.com/fraction/oasis/issues/98

Solution: This changes the main navigation to use links with the first
letter capitalized, like how Patchwork + Twitter + Mastodon + etc do it.
This means that we're consistently using sentence case everywhere, which
I think is our best option. Originally I tried experimenting with
all-caps for actions, which I found aesthetically pleasing, but you have
to reduce the font size to make it look good (bad!) and I was reading
that all-caps text is harder for friends with dyslexia or vision
impairments.

### CODE REVIEW

**Comment by christianbundy** [comment]
Screenshot!

Screenshot from 2020-01-27 15-56-20

(This screenshot has lots of other branches merged too)

**Comment by cinnamon-bun** [comment]
Looks good!

I don't have time to try out the branch right now but the code looks ok.  Do we want Maintainers to test everything manually before merging it?

**Comment by christianbundy** [comment]
> Do we want Maintainers to test everything manually before merging it?

I'm comfortable not doing this, just a quick glance at the code would be great. Really appreciate you noticing my backward `restart()` logic!

**Comment by jedahan** [comment]
I can try out the branch right now.

**Comment by christianbundy** [comment]
Thanks for the review and merge!

**Pull request merged**
