### PR TITLE
Better translations for Spanish

### PR DESCRIPTION
**Pull request by J053Fabi0**
## What's the problem you solved?
Some translations had orthography errors for Spanish and there were missing translations.

## What solution are you recommending?
I'm adding some missing translations and correcting those errors.

### CODE REVIEW

**Comment by J053Fabi0** [comment]
Is the error in the check my fault? I only changed strings.

**Comment by christianbundy** [comment]
Sweet! Could you run `npm run fix` and commit the changes please?

**Comment by J053Fabi0** [comment]
Awesome

**Comment by J053Fabi0** [comment]
I noticed that this strings have no label in the file to be translated:
image
image

**Comment by christianbundy** [comment]
Thanks again! Merging now.

> I noticed that this strings have no label in the file to be translated:

Yep. I'd be happy to merge a fix for that.

**Pull request merged**
