### PR TITLE
Add content warning publishing, fixes #191

### LINKED ISSUE #191: Allow for posting with content warnings
**What's the problem you want solved?**
I talk about developer stuff too much on scuttlebutt, and would like to hide that talk behind content warnings.

**Is there a solution you'd like to recommend?**
Have a second textbox under any post form for an option content warning

### PR DESCRIPTION
**Pull request by jedahan**
**What's the problem you solved?**
Could not publish content warnings from oasis

**What solution are you recommending?**
This thing

contentWarning

### CODE REVIEW

**Comment by jedahan** [comment]
its not i18n'd completely, and needs a better description, maybe up top. but it works! and we can improve it!

**Comment by christianbundy** [comment]
Dude! This is a great patch, I'm really excited to merge this. :tada:

**Comment by cinnamon-bun** [comment]
🎉 Thank you! 🎉

**Comment by jedahan** [comment]
btw I want to thank @myf and @andreemonette for their help with making this

**Pull request merged**
