### PR TITLE
Refactor Docker example

### PR DESCRIPTION
**Pull request by christianbundy**
Problem: The Docker example was using Alpine with the Tini dependency
and some neat custom stuff, but it wasn't super clear to understand
everything that was going on. It was also slow because lots of stuff was
compiling from source.

Solution: Replace neat custom stuff with boring defaults for clarity and
much faster builds.

### CODE REVIEW

**Comment by christianbundy** [comment]
cc: @murilopolese

**Comment by murilopolese** [comment]
Wow! Thanks so much for this!!! I’ll give a try tonight :)

**Comment by murilopolese** [comment]
It works, as expected! I'm digging into the onboarding now. :)

**Comment by christianbundy** [comment]
Woo! Please let me know if you have any trouble.

**Comment by christianbundy** [comment]
Open for a week, I'm gonna self-merge.

**Comment by murilopolese** [comment]
This worked like a charm! 
For learning purposes, was I supposed to do something else than verbal approval?

**Comment by christianbundy** [comment]
Nope, you did great. Usually maintainers don't merge their own pull requests, they wait for another maintainer to merge it, but after a few days if nobody says anything then maintainers will merge their own PR.

**Pull request merged**
