### PR TITLE
Fall back to TCP socket if Unix connection fails

### PR DESCRIPTION
**Pull request by christianbundy**
Problem: We're only attempting connection via Unix sockets, but some SSB
services may choose to only listen on TCP sockets.

Solution: Start by attempting connection to Unix socket and fallback to
the TCP socket remote if that doesn't work, before just trying to start
our own SSB service.

### CODE REVIEW

**Comment by christianbundy** [comment]
cc: @khimaros could you confirm that this fix works?

**Comment by khimaros** [comment]
@christianbundy -- great catch! This had nothing to do with caps after all.

Initially this didn't help because my `net` connection was not configured to listen on all interfaces (maybe oasis was looking for `127.0.0.1`?).

After setting `"host": "0.0.0.0"`, so that it listened on all interfaces, it worked. An alternative solution was adding `"unix": [ {"scope": "device", "transform": "noauth" }]`.

**Comment by christianbundy** [comment]
Thanks for confirming!

This *should* be using the `remote` property from your config, but if you don't have one then SSB-Client has [some defaults](https://github.com/ssbc/ssb-client/blob/e2ff27019657916cd13c8fb7a840f2675eaf4a1d/index.js#L31-L34), which would explain the problem.

**Comment by khimaros** [comment]
Though it isn't a panacea, this seems worth merging.

**Comment by sbillig** [comment]
Finally took the time to test this. Seems to work fine.

**Pull request merged**
