### PR TITLE
Added more spanish translations

### PR DESCRIPTION
**Pull request by seekr**
Added more spanish translations

### CODE REVIEW

**Comment by christianbundy** [comment]
🤯 This is wonderful, thank you for this patch!

**Comment by christianbundy** [comment]
Oh dang, could you run `npm test` locally? It looks like there's a duplicate key or something, You *might* be able to fix it with `npm run fix`, but I think you might need to delete one of the `search` entries.

**Comment by seekr** [comment]
> Oh dang, could you run `npm test` locally? It looks like there's a duplicate key or something, You _might_ be able to fix it with `npm run fix`, but I think you might need to delete one of the `search` entries.

upss... I didn't follow the protocol, let me fix this. I'll need to make another PR.

**Comment by christianbundy** [comment]
It's okay, you can just push a new commit to this PR! Here, I'll open a PR into your branch to fix it. :heart:

**Comment by seekr** [comment]
Done! ;)

**Comment by seekr** [comment]
FYI, I hope to continue on Spanish translations and then move to Portuguese translations.

**Comment by christianbundy** [comment]
Awesome! If you have any thoughts on how to improve the translation code please let me know!

**Pull request merged**
