### PR TITLE
Add automatic reconnection on failure

### LINKED ISSUE #40: Error: stream is closed
When opening oasis from systemctl --user start oasis, it fails. manually running it is fine I think.

**What version of this package are you using?**
@latest

**What operating system, Node.js, and npm version?**
debian testing, node v12.14.0, npm 6.13.4

**What happened?**
I cannot view localhost:4515 - this is the error:
```
Error: stream is closed
    at /home/micro/.config/npm/lib/node_modules/@fraction/oasis/node_modules/muxrpc/index.js:45:25
    at remoteCall (/home/micro/.config/npm/lib/node_modules/@fraction/oasis/node_modules/muxrpc/remote-api.js:40:19)
    at obj.<computed> (/home/micro/.config/npm/lib/node_modules/@fraction/oasis/node_modules/muxrpc/remote-api.js:25:18)
    at /home/micro/.config/npm/lib/node_modules/@fraction/oasis/src/pages/models/lib/cooler.js:71:15
    at new Promise (<anonymous>)
    at Object.read (/home/micro/.config/npm/lib/node_modules/@fraction/oasis/src/pages/models/lib/cooler.js:70:12)
    at Object.popular (/home/micro/.config/npm/lib/node_modules/@fraction/oasis/src/pages/models/post.js:438:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async publicPopularPage (/home/micro/.config/npm/lib/node_modules/@fraction/oasis/src/pages/public-popular.js:8:20)
```

**What did you expect to happen?**
to be able to see oasis

**Are you willing to submit a pull request to fix this bug?**
yes

### PR DESCRIPTION
**Pull request by christianbundy**
**What is the purpose of this pull request?** This automatically reconnects the client, starting an SSB service in the background if the connection fails repeatedly. Resolves #40.

**What changes did you make? (brief overview)** Added a check during `connect()` and if the stream is closed, restart the client. If the client can't connect, start the server.

**Is there anything you'd like reviewers to focus on?** Most of the changes are just whitespace changes from the indentation. When looking at *Files changed* you can hit the gear icon and select "hide whitespace changes".

Does this behavior sound right to you?

### CODE REVIEW

**Comment by jedahan** [comment]
First of all, thanks for teaching me about hide whitespace changes, that made it much easier to read.

Secondly, is there a way to only restart if we know the handle is an oasis-created sbot? Maybe some rpc status?

**Comment by christianbundy** [comment]
:tada: 

> Secondly, is there a way to only restart if we know the handle is an oasis-created sbot? Maybe some rpc status?

I'm sure we could figure something out. Could you maybe describe the problem you'd like to solve? When Oasis is connected to Patchwork, and Patchwork closes, I'm very happy to have Oasis start its own server. Are there use-cases where this wouldn't be desirable? Maybe we should have some sort of `--no-server` option for people who want to use Oasis in client-only mode?

**Comment by jedahan** [comment]
I’m mostly just worried about the potential of multiple writers. I know right now it’s up to the user but maybe this can be split off into a different discussion where we think about a more broad locking mechanism to avoid accidental self forks

**Comment by christianbundy** [comment]
That makes sense, maybe we could discuss in an issue or on a call, if you're down?

Would you like me to keep this PR unmerged until we discuss?

**Comment by jedahan** [comment]
I think this is merge-able as is (though I have not tested it yet, if you want, give me an hour).

Let's definitely hop on a call this week. I am EST, anytime after 11am works for me (currently getting over a cold).

**Comment by jedahan** [comment]
Hey, retry worked! I'm on a non-systemd system right now, but this should fix that issue I found.

**Comment by christianbundy** [comment]
Awesome, thank you! Is SSB the best way to get a hold of you? You're (@)micro, right?

**Comment by jedahan** [comment]
ssb is best for now, yes regarding the handle

**Pull request merged**
