### PR TITLE
Fix summary style

### PR DESCRIPTION
**Pull request by christianbundy**
Problem: the `<summary>` element had a broken bottom margin on content
warnings, and isn't obvious that it's not just text.

Solution: Fix the margin and used a dashed border to indicate that the
content can be expanded. I think this is more intuitive than no border,
and I think the dashed line draws parallels with "cut outs" that might
make expansion intuitive (?), but either way I think it's better than
the previous design.

### CODE REVIEW

**Comment by christianbundy** [comment]
cc: @nickwynja, I'd be curious to hear what you think about this.

**Comment by nickwynja** [comment]
I think this works nicely for content warning! It doesn't feel quite right for reply summaries though. It makes the reply jump out visually from the thread when the intent of the summary is to soften the effect of the reply in the overall thread. I'm not sure it would make sense to remove the border for `.indent > details > summary` though since we wouldn't be using the visual style consistently. Hmm.

**Comment by christianbundy** [comment]
Alternative: Is this too much contrast?

```css
section {
  border: var(--pico) solid var(--fg-status);
}
```

I recently found https://www.stayhometakecare.com/ and I'm kinda inspired by the aesthetic.

**Comment by nickwynja** [comment]
> Is this too much contrast?

It's maybe a little strong but that's subjective (and possibly dependent on which theme someone is using).

**Comment by christianbundy** [comment]
I don't mind removing the border on ` .indent > details > summary` if you prefer, just let me know. The important thing to me is that this patch doesn't cause more problems than it solves.

**Comment by nickwynja** [comment]
Yea, maybe it's most useful just on the content warning `<summary>` at this point.

**Pull request merged**
