### PR TITLE
2.17.0

### PR DESCRIPTION
**Pull request by cblgh**
Release changes added in https://github.com/fraction/oasis/pull/462 (among other PRs—it's been a while since a release was forged!)

More concretely, below is a changelog, as mined from the git log with `git log v2.16.0..HEAD --oneline` and deleting lines mentioning merging / linter stuff:

(Let me know if this release PR could be improooved!)
```
2.17.0
document quick fix for making the server definitively exit
try workaround
make code flow more shallow
fix race on blobs variable
restore common-good check & fix its errors
reset test/basic.js
manually edit package-lock
shuffle css around to make prettier / common-good happy
replace warning with comment
fix button sizes
pin deps
add simple test for blob uploads
fix common-good setup
invalidate @mentions cache if the user follows someone
fix @mentions lookup table
remove bracket from regex
add more delims, fix double nicknames
change name->feed lookup structure
improve mentions regex edge cases
add i18n for mentions component
add much improved mentions listing
some more comments
implement relationship-based name matching
some prefix matching logic
add german translations (thx cryptix)
add i18n.preview for all languages except .de, improve labels
delineate bottom border of summary details
some @mentions in preview
make subtopicView and commentView consistent w/ threads
remove superfluous padding top from post-preview2C
tweak post preview css
remove exif data from uploaded jpegs
add blob upload to comment, subtopics
implement content warnings for comments, subtopics
refactor previewView, fix displaying content warnings in previews
add subtopic previewing
extract preview code into generatePreview
condense threads in summaries view, as well
improve thread view
fix crash w/ no likes, improve preview styling
use file-type for mime and enhanced preview
whoops cleanup
implement comment previewing
extract preview code into generatePreview
condense threads in summaries view, as well
make like button the same size as other footer actions
improve thread view
ignore vim swap files
improve visual hierarchy by refining bold text use
begin working on preview with blobs
Add absolute post time as tooltip to timestamps.
Bump lodash from 4.17.15 to 4.17.19
Allow GET params in /blob calls.
Add rendering of blog messages.
Add simple pagination to user feeds.
Fix broken Profile Edit
Adds visual separator for threads
Adds mystery description fallback
adds title for imageSearch
Adds view specific titles
Improve wrapping of sticky section header
Refactor Docker example
Fix 'cannot set autostart of undefined'
Upgrade Flotilla and SSB-CONN, remove auto-stage
Apply style fixes
Add i18n for image search
Add sidebar entry
Add image search
Rename "reply" to "subtopic"
Remove dashed summary style from indented summary
Replace "metric CSS" with --size-N
Fix summary style
Add timeout to sync and refactor
Fix allow-host preset not working correctly
Use target for progress checks
Refactor peer checking
Progress checking and connected peers
Introduces sync endpoint
```

### CODE REVIEW

**Comment by cblgh** [comment]
fwiw: looks like the build passes on all but two of travis's jobs: 
```
926.4
AMD64
Node.js: lts/dubnium
---
926.5
AMD64
Node.js: lts/erbium
```

the only error message: `An error occurred while generating the build script.`

**Comment by christianbundy** [comment]
Thanks for making this release! I'd like to let #462 bake in master a bit before releasing, and if feels important to me that problems like #465 and #466 are solved. I'm wary of releasing new features that break simple behavior, so I'd really like to get those problems fixed before releasing to the general public.

Maybe we can aim for Nov 30? Hopefully that should be enough time for at least one of the developers to be able to get Oasis ready for release.

**Comment by cblgh** [comment]
@christianbundy sounds reasonable to me! the only thing i see myself working on as regards the mentioned issues is maybe https://github.com/fraction/oasis/issues/466, but no guarantees on my end atm :)

**Comment by cblgh** [comment]
another thing that would be ace to get in is this contacts view that @cryptix and i made as well https://github.com/cryptix/ssb-oasis/tree/contactzzz :3



(i think cryptix was going to rebase & pr it soonish :~)

**Comment by christianbundy** [comment]
Once #521 is merged I think I'd be happy to cut a new release -- maybe you could rebase when you have time (or just make a new PR with a version tag)?

**Comment by christianbundy** [comment]
(Or I can just release, just don't wanna steal your thunder here.)

**Comment by cblgh** [comment]
@christianbundy feel free to release how ever you want! i'm happy as long as stuff lands 😊

**Comment by christianbundy** [comment]
Rebased and opened as #531 :heart:

**Pull request closed without merging**
