### PR TITLE
Add build script that creates zip files

### PR DESCRIPTION
**Pull request by christianbundy**
Problem: Most people don't have npm installed and we probably shouldn't
force them to have a full development environment to use Oasis. It would
be nice to have a way to install Oasis without any development tools.

Solution: Add a build script that can create .zip files that work on
Unix systems like macOs and Linux. Users will need to download the zip,
extract it, and double-click the `oasis` script. This script will run
`npm start || npm install && npm start`, which uses binaries that we
ship in the zip file so that they don't need to have `node` or `npm`
installed.

### CODE REVIEW

**Comment by christianbundy** [comment]
I don't think we should merge this unless the binaries in #172 actually work. Otherwise this isn't useful at all.

**Comment by staltz** [comment]
I think node-gyp may use the env var `ARCH`, and the way of setting might be via npm global variables: https://github.com/nodejs/node-gyp/#configuration

I don't know too well how to do this, sorry. What about https://github.com/zeit/pkg or https://github.com/zeit/ncc ?

**Comment by staltz** [comment]
Hmmmmmmmm interesting https://github.com/zeit/pkg/commit/1db8310508171c50e389fb119f418a4361d307fe

**Comment by christianbundy** [comment]
Replied to the above in `%ILdFFMAgYfR8eibtBcHimnufYL2Ynnl7ireTJc2fRYY=.sha256`, for anyone following along.

**Comment by christianbundy** [comment]
I'm feeling much better about this branch now. Instead of running `npm install` on the target device we're just checking our 3 native modules and ensuring that the prebuilds are configured correctly. This means that the zip contains all of our source and all of the binaries, and the script is mostly there because `node` and `npm` aren't already available in our path. The caveats:

- On macOS we still need to have people go into their settings and circumvent the "Oasis is from an unidentified developer" thing.
- On Linux we need to rename the file to end with `.AppImage` or something so that we can get it to open with a double-click.
- If you try to run sodium-native or leveldown on a platform or architecture without prebuilds, it'll try to build from source. Should I remove this?

**Comment by christianbundy** [comment]
macOS: https://send.firefox.com/download/0b895876f1e422f6/#uwn6uQxwMHgFP2G9WRKAeg

Linux: https://send.firefox.com/download/cc4bec7ea06a41f5/#qVe3GineLKO8fdyAcZ2B3w

**Comment by christianbundy** [comment]
^ cc: @georgeowell

**Comment by georgeowell** [comment]
> macOS: https://send.firefox.com/download/0b895876f1e422f6/#uwn6uQxwMHgFP2G9WRKAeg
> 
> Linux: https://send.firefox.com/download/cc4bec7ea06a41f5/#qVe3GineLKO8fdyAcZ2B3w

Wow @christianbundy, this is working really nicely for me on Ubuntu 18.04. I did have to use the terminal to launch it though as otherwise the script just opened in a text editor.

I think honestly this isn't too bad. Oasis is still pretty new so we don't necessarily have to aim for less technical users right now. We want to attract people who can help with all the small simple issues on Github really and this is a big step up. We can always add other install methods in the future.

Would this approach work on Windows? Maybe we can ask Soapdog.

p.s. Just a thought, how does Tor Browser handle this? You download a Zip, extract it then click a launcher and it integrates into your menu afaik.

**Comment by christianbundy** [comment]
That's great to hear!

> I did have to use the terminal to launch it though as otherwise the script just opened in a text editor.

Yeah, on Linux we need to rename the file to end with .AppImage or something so that we can get it to open with a double-click.

> Would this approach work on Windows? Maybe we can ask Soapdog.

This particular code would not, because it relies on `/bin/sh` but we could write most of the script in Node.js and then just have shell/batch that find the `node` binary and run our code? Or maybe there's a better way to do it, I haven't spent enough time thinking about the best way to support Windows.

**Comment by christianbundy** [comment]
Just added the `.appimage` hack, here's a version with double-click working:

https://send.firefox.com/download/b323fb14827d8ddc/#CX11M-KpwxMfTZtQxsyVpw

**Comment by christianbundy** [comment]
Two problems I've identified with running as an AppImage (no terminal):

- There's no way to exit Oasis. Closing the tab just closes the interface, but the server keeps running indefinitely. Maybe we should have a way to exit from the settings?
- There's no way to see errors. If you double-click the executable and it prints "Something is already running on port 3000, please try another port" then the user will never see it because they don't have a terminal open. I built [http-alert](https://github.com/christianbundy/http-alert) to experiment with doing `alert()`s from Node.js without having to use Gtk/Qt, but I had a friend ask "why don't you just print to a file and open *that* with the browser" and that honestly sounds really reasonable.

**Comment by georgeowell** [comment]
> Two problems I've identified with running as an AppImage (no terminal):
> 
>     * There's no way to exit Oasis. Closing the tab just closes the interface, but the server keeps running indefinitely. Maybe we should have a way to exit from the settings?
> 
>     * There's no way to see errors. If you double-click the executable and it prints "Something is already running on port 3000, please try another port" then the user will never see it because they don't have a terminal open. I built [http-alert](https://github.com/christianbundy/http-alert) to experiment with doing `alert()`s from Node.js without having to use Gtk/Qt, but I had a friend ask "why don't you just print to a file and open _that_ with the browser" and that honestly sounds really reasonable.

Yep was just about to post the same thing! What's alert()s sorry?

**Comment by christianbundy** [comment]
> What's alert()s sorry?

https://jsfiddle.net/kbnjtq29/1/

:~)

**Comment by christianbundy** [comment]
Obligatory Darwin build for macOS butts: https://send.firefox.com/download/d238ce434de38832/#GM7pReIp_KcO3Ei_jDJXXQ

**Comment by georgeowell** [comment]
> > What's alert()s sorry?
> 
> https://jsfiddle.net/kbnjtq29/1/
> 
> :~)

I mean I assumed it was that :smile:

**Comment by christianbundy** [comment]
This is getting unreasonably hacky, but holy shit it works.

https://send.firefox.com/download/f91f8fafb3d11ea8/#aqX6XAe4hXb9lLemv_JE7A

**Comment by christianbundy** [comment]
UNIVERSAL (x64) INSTALLER: https://send.firefox.com/download/f0cf41134ec61c25/#jmgV5A4S5ZJtCXdxeHT8Zw

This is a hard problem. :/

**Comment by georgeowell** [comment]
> UNIVERSAL (x64) INSTALLER: https://send.firefox.com/download/f0cf41134ec61c25/#jmgV5A4S5ZJtCXdxeHT8Zw
> 
> This is a hard problem. :/

Whoa! This is so fast. Works like a charm on Linux. Now we just need to test Mac and Windows and you may have cracked this.

**Comment by christianbundy** [comment]
Friends reported a problem with the macOS build, so I've just pushed a fix. New zip here:

https://send.firefox.com/download/50cad83d090fb1ca/#AhKG1cwinHvt4kpnAL9L8A

**Comment by christianbundy** [comment]
New binaries: https://send.firefox.com/download/d48632da162c54df/#au0CZafnP_Nu1ExWu_VPpw

cc: @cryptix please roast me

**Comment by georgeowell** [comment]
Shall we merge this and then open specific issues for any bugs found?

**Comment by christianbundy** [comment]
Yep, this wasn't meant to be a WIP branch. It's good to merge. :+1:

**Comment by christianbundy** [comment]
What do you think about this PR @jedahan?

**Comment by christianbundy** [comment]
I don't think anyone has capacity to review pull requests right now, so I'm going to self-merge this.

**Pull request merged**
