### PR TITLE
Change favicon dimensions to fit in tab

### PR DESCRIPTION
**Pull request by christianbundy**
**What's the problem you solved?** Some of the icon was being clipped in my browser. I think that this is because the SVG text actuall extends down under the line (like a `g` or `y`).

**What solution are you recommending?** Change SVG viewBox dimensions and SVG size to fit correctly.

Before and after:

Screenshot from 2020-01-23 13-42-47

### CODE REVIEW

**Comment by cinnamon-bun** [comment]
This looks good to me.  I'm not listed as a reviewer so I'm leaving it for @jedahan.

I'm amused by this trick of using an emoji inside an SVG :)

**Comment by christianbundy** [comment]
Oh, feel free to merge -- I probably should've just CC'd instead of assigning for review.

**Comment by jedahan** [comment]
Somehow gits merging algorithm reverted the change. Fixing in this PR.

**Comment by jedahan** [comment]
(i wonder if pijul would have done it right...)

**Pull request merged**
