### PR TITLE
Add simple nav sidebar on large screens

### PR DESCRIPTION
**Pull request by christianbundy**
Problem: Putting the navigation at the top of the screen makes it
impossible to use when you're scrolling through a page, which isn't a
good user experience. It was never meant to be permanent, and I think
everyone has pointed out that it's been a pain. See #28.

Solution: Super simple sidebar nav when people are on bigger screens.
This doesn't solve the problem on mobile, and it doesn't incorporate the
'popular' page's interval settings, but I think it's a step in the right
direction.

### CODE REVIEW

**Comment by christianbundy** [comment]
Screenshot from 2020-01-27 12-36-15
Screenshot from 2020-01-27 12-35-57
Screenshot from 2020-01-27 12-35-40
Screenshot from 2020-01-27 12-35-22
Screenshot from 2020-01-27 12-35-06

**Comment by christianbundy** [comment]
The merge history looks super janky but the weird sidebar movement problem is solved!

**Comment by jedahan** [comment]
How do you feel about rebase and merge?

**Comment by christianbundy** [comment]
> How do you feel about rebase and merge?

Happy to do it if you'd like, but not something I'd do recreationally. Usually I try to avoid rewriting Git history unless I *really* mess something up, like committing to the wrong branch, but if it's important to you I have no problem taking a few minutes and making my branch prettier.

**Comment by jedahan** [comment]
Oh I didn’t mean rebase, I meant if I squashed on merge.

**Comment by jedahan** [comment]
personally seeing 4 merge commits in a 7 commit history seems like unnecessary noise

**Comment by christianbundy** [comment]
I'm conflicted -- on one hand, it'd be nice to have one commit per patch, but on the other it feels bad to rewrite the actual development history (especially with commit messages) and replace it with something simple. Feels like a 'hard truth vs simple lie' sort of thing.

If you think that's best I'm happy to follow your lead. Or we could discuss in #54 if you'd prefer? :man_shrugging: It's up to you, I trust your judgement here.

**Comment by jedahan** [comment]
I'm going to try rebase and merge on this PR to see exactly how github does it, and then discuss how we should do it in the future.

**Pull request merged**
