### PR TITLE
Redirect search to SSB references

### PR DESCRIPTION
**Pull request by christianbundy**
Problem: There wasn't an easy way to copy and paste a message ID, feed
ID, or blob ID and get directed to that page in Oasis.

Solution: When someone pastes one of the above into the search, just
redirect the browser to the correct page rather than searching for that
text.

### CODE REVIEW

**Comment by christianbundy** [comment]
Thank you!

**Comment by cinnamon-bun** [comment]
Hooray, this makes it much easier to jump between Patchwork and Oasis :D

**Comment by christianbundy** [comment]
Woooo!

P.S. Maybe the search should just be always available on the sidebar? :man_shrugging:

**Comment by jedahan** [comment]
I love always available search.

**Comment by cinnamon-bun** [comment]
Would it make sense to do this for hashtags also?  Searching for #foffee sends us to

http://localhost:3000/search?query=%23foffee

Which is different than clicking a hashtag link in a message, which goes to

http://localhost:3000/hashtag/foffee

I'm unclear on the differences between those two views.  `/hashtag/` is looking for SSB channels (which we don't render)?

**Comment by christianbundy** [comment]
> Would it make sense to do this for hashtags also?

Yep, I think that's a great idea.

> `/hashtag/` is looking for SSB channels (which we don't render)?

Yeah, I'm not excited about supporting channels or encouraging their use unless we can really nail the ergonomics, but we should maybe at least do something like:

```javascript
if (message.value.content.channel != null) {
  message.value.content.text += `\n\n#${message.value.content.channel}`
}
```

So that if someone publishes a message with channel #foo, we at least display it at the end of their message.

#foo

**Pull request merged**
