### PR TITLE
Convert .travis.yml to GitHub Action

### PR DESCRIPTION
**Pull request by christianbundy**
## What's the problem you solved?

#480

## What solution are you recommending?

GitHub Action, unfortunately. :/

### CODE REVIEW

**Comment by black-puppydog** [comment]
OMG windows and its line endings... :facepalm:

**Comment by christianbundy** [comment]
SERIOUSLY. I think there's a way to fix it with `.gitattributes` but I am lazy and I just want the dependency PRs merged. I'm so frustrated that Travis just fell over and died on us. :sob:

**Comment by christianbundy** [comment]
I'm gonna quick-merge this to unbreak the other builds, please let me know if you'd like to see any changes anywhere. :grimacing:

**Comment by black-puppydog** [comment]
nah, this looks good to me. but you're admin for this repo so I guess you'll have the glorious task of cleaning up after travis' new pricing plans: 

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

FWIW they cite recent rise of abuse (Tor, cryptocurrency mining...) as the reasons and that it was actually degrading performance. which... fine, I guess...

they also say FLOSS projects can simply write to customer support and get moar minutes. We're not doing anything extravagant here, so might be as simple as that.

**Pull request merged**
